### ISSUE TITLE
Pooper range is X / 5 on the vendor list, but X / 10 on the details

### ISSUE THREAD

**Issue by matejdro** [urbandroid-team/dont-kill-my-app#1]
On the vendor list page, there are 5 pooper icons, but when you click on the vendor, it shows 10 icons (last 5 icons are always empty).

![image](https://user-images.githubusercontent.com/507922/50660563-84e07f80-0fa0-11e9-98eb-bbeea96341bc.png)

Is this intentional?

**Comment by Artaud** [comment]
Thanks! Fixed with c056901c60bad490fb2b5bc0238fca989e5bb0ad
