### ISSUE TITLE
Nokia replaced Evenwell with Android's Adaptive Battery

### ISSUE THREAD

**Issue by ElegyD** [urbandroid-team/dont-kill-my-app#100]
See here:

https://community.phones.nokia.com/discussion/51246/tapping-into-android-pies-adaptive-battery-for-optimum-battery-performance

**Comment by louistsaitszho** [comment]
Added in https://github.com/urbandroid-team/dont-kill-my-app/commit/6e87069787c82b6ba302a0c50f700b9de037f757

**Comment by YoRyan** [comment]
The announcement makes no mention of Duraspeed, which is still active by default on my MediaTek 3.1 as of the August maintenance update.

**Comment by Artaud** [comment]
Right - we've changed the Nokia page description but left Duraspeed issues in.
