### ISSUE TITLE
Feedback for Sony page

### ISSUE THREAD

**Issue by leewp14** [urbandroid-team/dont-kill-my-app#107]
> It is called Stamina mode and it instantly breaks all background processes and all alarms if enabled.

I think that the Sony Stamina is updated in many ways, and with a balanced power saving stamina mode, I didn't notice any difference in the behavior of background process. The new stamina mode is different with the old stamina mode in some ways (ie limiting graphic and cpu performance etc). I didn't add any app to the exceptions at all till date. Whatsapp web worked fine without opening whatsapp on the phone, notifications arrive on time, basically for me at least there's nothing wrong. 
Also for newer Sony there's a smart memory management feature under the Sony Assist in Settings. I have that enabled too. 
Overall, everything is just fine for me. I could be wrong too :) Just trying to share my thoughts.

**Comment by weiss** [comment]
Isn't Stamina mode actually disabled by default these days?  I don't have a Sony device myself, but from what I've seen on other people's phone's, Stamina seems to be opt-in.  In which case I think the feature is fine.  As far as I can tell, users don't run into any Sony-specific app killing issues at all, at least if they stick to default settings.  Therefore, the [negative rank][1] seems somewhat misleading to me (the reasoning of Sony having "opened the Pandora’s box" doesn't really seem relevant to end users, in my book).

[1]: https://dontkillmyapp.com/sony

**Comment by petrnalevka** [comment]
Hello, many thanks I think you are right.. Sony was the first who started to break apps in non-standard ways, but now we hardly hear about issues on support. So maybe it is right to give them just one thumb down.. But the one thumb they deserve IMHO as enabling Stamina still breaks alarms..so this is compliant with our scoring policy:
https://dontkillmyapp.com/about_score

**Comment by weiss** [comment]
Thanks for reconsidering!

> But the one thumb they deserve IMHO as enabling Stamina still breaks alarms..so this is compliant with our scoring policy:

I see how this complies with the policy, though personally I don't quite agree with that policy :smiley:   I think it's just fine to temporarily break functionality for the purposes of battery savings _if the user explicitly asks the OS to do so_.  Whatever, I guess this discussion is off-topic here :smiley:

**Comment by petrnalevka** [comment]
I would agree with that, if the OEM would do an excellent job on explaining users what is happening.. but honestly this is not even possible as users don't read disclaimers anyway..  when stamina was introduced we got hundreds of people complaining "why is my alarm broken?". They had absolutely no idea that stamina would be anyhow related to their alarm clock not working.

Nowadays it is not so common, but still.. there is a standard feature in AOSP called Background restrictions in App settings, so IMHO stamina mode is just another vendor-specific extension to the Android's battery management which will just confuse users and make thinks worse..

**Comment by weiss** [comment]
> there is a standard feature in AOSP called Background restrictions in App settings, so IMHO stamina mode is just another vendor-specific extension to the Android's battery management which will just confuse users and make thinks worse.

Right, that makes sense to me.  Thanks.
