### ISSUE TITLE
Feedback for Xiaomi page

### ISSUE THREAD

**Issue by ali32768** [urbandroid-team/dont-kill-my-app#109]
Sorry but this instruction is not for miui10. It maybe for miui7.

**Comment by aigun** [comment]
You should check hidden battery optimizations on miui 10

http://webcache.googleusercontent.com/search?q=cache:http://en.miui.com/thread-5771977-1-1.html&ved=2ahUKEwi2ntaP_LTlAhXQfZoKHeSND6sQrAIoATAJegQIBBAJ&usg=AOvVaw3PunIrlVoj0fQrojbNtgba&cshid=1571922764212

**Comment by petrnalevka** [comment]
Hello, big thanks for reporting you mean the whole listing for Xiaomi, or you mean something in particular?

**Comment by ali32768** [comment]
Hi.My phone is Xiaomi Mi9T.But hidden battery optimization did not fix my problem.






Sent from Yahoo Mail on Android 
 
  On Tue, 29 Oct 2019 at 16:18, Petr Nalevka<notifications@github.com> wrote:   
Hello, big thanks for reporting you mean the whole listing for Xiaomi, or you mean something in particular?

**Comment by Artaud** [comment]
What do you mean by hidden battery optimization?
1) The Autostart permission?
2) The MIUI optimization in developer options?
