### ISSUE TITLE
Does exiting apps using the home button instead of the back button have any effect on battery life?

### ISSUE THREAD

**Issue by debopriyobasu** [urbandroid-team/dont-kill-my-app#11]
A paranoid user always exits from apps using the back button thinking that if the home button is used to exit apps, it keeps running in the background, draining the phone's battery. How true is this assumption?
The back button and the home button analogy has always been very confusing for Android because a lot of apps behave like they are in memory, even if the back button is pressed, for example Google Chrome and Microsoft Word/Excel/PowerPoint. On the other hand, many apps start up afresh after they have been exited using the back button. In this situation, what would be the best method for Android users to exit apps. so that they function properly, while not draining their phone's battery running unneccesary services?

This question needs to be addressed so that users, regardless of the phone manufacturer, are well informed when to kill an app and when not to, so that it can do its function properly.

**Comment by petrnalevka** [comment]
Hello, this is wrong. Home or back does not matter, but ideally you keep your apps running and leave task management to Android. This really is the best you can do. 

Even when you would swipe them from recents you will hardly be more effective than the Android process management which takes care of this for you. It will probably just consume more resources to load the process back when needed.

"what would be the best method for Android users to exit apps" - Once again.. don't exit apps, Android is not windows. Android does task management for you more efficiently than you would do it manually.

If you have badly behaving apps which consume too much resources and they do not do a job which necessary for you.. just uninstall them, or if you want to keep them, just force stop them or - ONLY IF YOU KNOW WHAT YOU ARE DOING! - restrict their background processing..
