### ISSUE TITLE
Could the word "crap" be replaced with "negative"?

### ISSUE THREAD

**Issue by diachedelic** [urbandroid-team/dont-kill-my-app#117]
I know that we, as developers, are very frustrated by the behaviour of these devices, but perhaps the first paragraph of the (*user*-facing) website should not contain the word "crap"? Similar to #16, this gives a less than professional impression, especially as users will often be reading this immediately after opening an app for the first time.

We are planning to use [doki](https://github.com/doubledotlabs/doki) instead of redirecting users to the website, but I felt I should probably mention it as some folk will find it off-putting (my manager for instance).

In my opinion "negative score" is just as clear, or clearer, than "crap score".

**Comment by petrnalevka** [comment]
You are right I guess. There is an interesting phenomenon that some bad words may not sound that bad to you if you are not native in that language. For me the word crap sound similar to garbage or similar.. but probably it sounds more rude to natives.

**Comment by diachedelic** [comment]
Thats a funny phenomenon, [this programmer mentions it too](https://fossil.instinctive.eu/libsoldout/wiki?name=about-the-name).

**Comment by petrnalevka** [comment]
I did push it now. Thanks for the link

**Comment by diachedelic** [comment]
We really appreciate the quick response, my manager sends many thanks!

**Comment by petrnalevka** [comment]
Many thanks, we really feel about this as a community common project to centralize all the individual efforts different devs are putting into this in one place. So it makes sense to try to find the best form which is suitable most devs..
