### ISSUE TITLE
Solution to prevent app killing at OnePlus deviced

### ISSUE THREAD

**Issue by paarnoutse** [urbandroid-team/dont-kill-my-app#12]
Added as an "issue" here (don't know an other method to submit suggestions here), but intended as information to help people to prevent problems due to crazy app killing behavior at some devices.
See https://forum.xda-developers.com/showpost.php?p=78588761&postcount=7

**Comment by ol-v-er** [comment]
I confirm that "Lock the app in your 'Recent Apps' list" works for avoiding the system to enable the battery optimisation automatic switch on.
