### ISSUE TITLE
Autostart Managers

### ISSUE THREAD

**Issue by judemanutd** [urbandroid-team/dont-kill-my-app#123]
Hey guys, I'm curating a list of autostart managers for phones so the user can directly be taken to the autostart screen for their respective oem. I currently have XIAOMI working but that's only because I personally own a XIAOMI device. I would encourage people to try out the library and definitely create a few PR's so we can get more oems working. 

I just wanted to put this out here so users who do stumble upon this page can use this code in their app which may hopefully solve a few issues.

https://github.com/judemanutd/AutoStarter

**Comment by judemanutd** [comment]
Thanks @petrnalevka and good luck for your presentations.

**Comment by petrnalevka** [comment]
Hello Jude, I did add a reference to AutoStarter here if that is fine https://dontkillmyapp.com/apidoc.. I think it will get a very good visibility so hopefully you will soon get some feedback on the missing vendors.. that would be great. I would use your library in my own projects as this is really helpful..

**Comment by judemanutd** [comment]
woaaah! This is super @petrnalevka thanks so much for that and I hope so too. Again great job maintaining this doc and the repo, fabulous job!!

**Comment by petrnalevka** [comment]
Big thanks and crossing my fingers! Great job!
