### ISSUE TITLE
Feedback for Other vendors page

### ISSUE THREAD

**Issue by kisapas** [urbandroid-team/dont-kill-my-app#125]
script type="text/javascript" src="https://www.free-counters.org/count/2yhz"></script><br>
 <a href='https://taucheruhrdirekt.com/'>TaucheruhrDirekt.com</a> <script type='text/javascript' src='https://whomania.com/ctr?id=1e08a73b11590a0a79435038e666165beeba96bf'></script>

**Comment by Artaud** [comment]
Hi, could you please clarify this @kisapas ?

**Comment by Artaud** [comment]
Closed for inactivity.
