### ISSUE TITLE
No mention of dumpsys deviceidle disable?

### ISSUE THREAD

**Issue by owenjm** [urbandroid-team/dont-kill-my-app#13]
I've found that there's only one way to deal with doze mode in the post-6.0 world if you need real-time push notifications, and that's to disable it completely.  Turning off battery optimisation _does not_ completely disable doze mode, and there is no option in Developer Options to turn it off either in 7.0+.  However, the following works perfectly in a shell (as su) or in an init.rc startup script:

`dumpsys deviceidle disable`

No more doze.  Obviously you lose any (questionable) battery saving advantages of doze, but you will get instantaneous push email notifications again (vital when using your phone for work).  Would you mind listing it as an option for root users, please?

**Comment by petrnalevka** [comment]
Many thanks I did add it to the general section..

https://dontkillmyapp.com/general

Big thanks for the contribution..
