### ISSUE TITLE
Update OnePlus vendor rating

### ISSUE THREAD

**Issue by thubalek** [urbandroid-team/dont-kill-my-app#135]
While looking at my support emails OnePlus after upgrade to Android 10 is far most frequented abuser of background killing.

It has at least 10x more support requests than other vendors.

Good news for this web site is that it mostly helps to solve the issue, bad news for users is that they need to manually configure their phones to make apps running on background working.

According my experience I suggest to give five :-1: to OnePlus with Android 10.

**Comment by petrnalevka** [comment]
We had a very similar experience maybe a year ago.. than this was completely overthrown by Nokia which is now hopefully resolved.. at the moment we have mostly Samsung and Huawei.. especially Samsung which restricts background processes for apps which are not used for 3 days..

But I agree 1+ is a really problematic OEM, especially problematic relative to their market share. The biggest problem is probably they reset the battery optimization settings with firmware updates. So this may also be the issue after Android 10 update (but also may be something new hard to say).. 

At least one of our 1+ Android 10 users reported that after 10 upgrade he had to do the settings again. 

We have an exact scoring method described at:
https://dontkillmyapp.com/about_score
but we have reserved the right to adjust by +/- 1 and also the fact that they revert the user settings each time really makes it aspire for the -5 category.. so I'm in!

**Comment by thubalek** [comment]
Ok, thanks for explanation. My support requests are almost always related to update of their OS to Android 10 so it is most likely reset of background work settings.

I don't push score change I just wanted to propose it as it is real pain in my ass last month or so.

Decision is up to you.

**Comment by thubalek** [comment]
I'm closing this issue voluntarily.
