### ISSUE TITLE
Feedback for Samsung page

### ISSUE THREAD

**Issue by tmmelo** [urbandroid-team/dont-kill-my-app#137]
Disable adaptative battery too?  Text says disable all toggles but in image , adaptative battery is on

**Comment by petrnalevka** [comment]
Hello Tiego, do you have some insight that this is really needed? In fact maybe adaptive battery is the ASOP adaptive battery implementation which we do not have reports it should be causing issues... many thanks for the details..

**Comment by Artaud** [comment]
Yes, I believe that Adaptive battery can stay enabled.
