### ISSUE TITLE
Add option to hide score indicators?

### ISSUE THREAD

**Issue by liamjones** [urbandroid-team/dont-kill-my-app#150]
I'm aware we can use https://dontkillmyapp.com?[Icon_Number] to change the style of the score icons displayed.

Any chance of adding a way of hiding the score entirely?

**Comment by Artaud** [comment]
Hi, that wouldn't be difficult, PR is welcome :)

What would be the use case? If it's something that could be useful for more people, I'll do it.

**Comment by liamjones** [comment]
The use case is we'd like to link our users to DKMA for instructions on how to sort out device-specific notification issues (using the 'app' parameter so they only see the user docs) but don't want to say, in effect, "your device gets 5 thumbs down". Some users don't like being told their device is at fault for them not receiving notifications (even if that is the truth!)

I was going to submit a PR rather than an issue but I was having trouble getting the ruby native modules to compile so I could build the project. I can probably find time to have another go next week.

Any preference on how the implementation would work? I was thinking the simplest change would be to treat [Icon_Number] 0 as a special value but I could also look at doing a different parameter entirely if that's preferred.

**Comment by Artaud** [comment]
Well what you say kind of already works. 
When you supply a ?0 parameter to the URL, the site will try to load the thumbsdown images but will get stuck at placeholders which are just decent dots. So you effectively remove the negative images.

However it's not a _proper_ solution. I'm adding the ?0 parameter explicitly so that it will not show any images at all.

**Comment by Artaud** [comment]
Done in d2d2d9787291878ba89aec92eae853646bca9f94

**Comment by liamjones** [comment]
Thanks @Artaud!
