### ISSUE TITLE
Is it possible to replace the poop image with something more professional?

### ISSUE THREAD

**Issue by yccheok** [urbandroid-team/dont-kill-my-app#16]
Hi, thanks for creating this site. It become a useful resources, where we can send to our customers, during customer support.

However, is it possible to replace the poop image with something more professional? (Like a battery drained icon?) So that we can apply these valuable info in a more professional way. (For customer support purpose, including it as part of FAQ, ...)

Thank you!

**Comment by Artaud** [comment]
Hi, big thanks for starting this discussion. You are the second developer to disagree with the poop choice :)
We spent many hours trying to find out the best presentation for the negative award, and ended up with what we started with, which is the poop icon. I'll try to list what we came through, and why we didn't stick with it.

We're definitely not saying that it has to be poop, we understand that it may be offensive to some people, but everything we could think of was either offensive as well or just didn't carry the message across.
Definitely open for suggestions. 

The requirements for the icon are:

- it has to carry a clearly negative message, like "the more icons, the worse effect"
- it has to be generally and internationally understandable across developers and non-tech users alike

So what we came through was (with the reason why we decided not to go with it):

- icons that had something to do with killing or death (skull, knife, gun, zombie)
  - violent and probably offensive, worse off than poop
- brick (as in, with those manufacturers, your phone would be useful just as a brick)
  - not universally understandable, not negative at first glance, also quite difficult to schematize recognizably
- iphones (as in, iphones have big restrictions in background processing)
  - probably too geeky, not understandable, laymen could take it as a positive symbol (LOL)
- a man with crutches, wheelchair
  - offensive in this context
- Dementor from Harry Potter
  - impossible to schematize
- radioactivity symbol
  - doesn't make much sense
- dynamite, bomb
  - either violent or could be taken in a positive light 

Drained battery symbol would actually be the other way around - the vendors try to get you as much battery as possible so it would turn the whole message of the site over unfortunately...

Poop is a natural human product that in an ideal world noone should be offended about :(

It's a pretty big issue to come up with something representative.

**Comment by yccheok** [comment]
Thanks for speedy reply.

I understand it is difficult to have an icon to represent battery drain.

How about using a "thumb down icon"?

**Comment by yccheok** [comment]
> Some more ideas:
> 
> * trojan horse (may be easy to depict)
> * wolf masked as a sheep
> 
> So with regards to keeping everyone happy, we decided to add a parameter to the site which will change the award images, like so:
> 
> dontkillmyapp.com/nokia?1
> 
> What do you think?

Yes. I would happy to utilize such feature so that our FAQ/ Google Play store description (Currently, we include such link in our Google Play store description page) would look more professional.

**Comment by Artaud** [comment]
I did 4 parameters for starters

- https://dontkillmyapp.com/?1 Stalin
- https://dontkillmyapp.com/?2 Poop
- https://dontkillmyapp.com/?3 Thumbsdown
- https://dontkillmyapp.com/?4 Trojan horse

And https://dontkillmyapp.com has the default poop

**Comment by yccheok** [comment]
<img width="281" alt="2019-01-09 18_40_38-don t kill my app _ hey android vendors don t kill my app" src="https://user-images.githubusercontent.com/308276/50894444-3c144500-143e-11e9-8b34-af24dfceb2a8.png">

Thanks for speedy respond.

I think for thumb down, it isn't very clear, whether an icon is off/on. For instance, for OnePlus, it isn't obvious whether we have 5 thumb downs, or 4 thumb downs. Perhaps 

1) Use outline instead of fill color, for off-ed icon?
2) Or even better, make the off-ed icon invisible?

**Comment by Artaud** [comment]
Okay I used outline and also added customization icons down in the footer for easy access

**Comment by bubbleguuum** [comment]
I also would like a different icon.
The problem with the poop icon is not the poop itself but that if you send users to this site from your app, it may give user the impression that you (the developer) are trying to tell them their device is shit. It may well be, but that's not a message you want to send as a developer.

**Comment by Artaud** [comment]
Sure no trouble, I'll add the trash can, great idea!

**Comment by Artaud** [comment]
Added as ?5 parameter with 20ae4883358ed1e46975263340a4d89d02ac50ec

**Comment by Artaud** [comment]
Also please check out the commit - it is very easy to add any other image and do a pull request - I really encourage everyone to do so!
