### ISSUE TITLE
Support for multiple languages.

### ISSUE THREAD

**Issue by Malachiasz** [urbandroid-team/dont-kill-my-app#167]
Do you have a support for translations? If not could you provide one if we offered to translate the content to German?

**Comment by TCattd** [comment]
Came looking for the same thing.

(If it's implemented) Can help with Spanish if needed.

**Comment by Artaud** [comment]
We discussed this to a great extent in https://github.com/urbandroid-team/dont-kill-my-app/issues/19 and recently reached a solution using GitLocalize.

If you want to help translate, please follow the instructions in https://github.com/urbandroid-team/dont-kill-my-app/issues/19#issuecomment-607819532

Big thanks for the initiative!
