### ISSUE TITLE
Feedback for Samsung page

### ISSUE THREAD

**Issue by leodoi3** [urbandroid-team/dont-kill-my-app#204]
There is a "apps that wont be put to sleep" section. What happens if the app is added there?

**Comment by robertsimmons514** [comment]
@ol-v-er

**Comment by robertsimmons514** [comment]
> There is a "apps that wont be put to sleep" section. What happens if the app is added there?

**Comment by robertsimmons514** [comment]
https://github.com/urbandroid-team/dont-kill-my-app/issues/204#issue-634836905

**Comment by robertsimmons514** [comment]
### 

- _**

1. 

**_
