### ISSUE TITLE
Nokia 1, app not in list or "Failure [not installed for 0]"

### ISSUE THREAD

**Issue by Mikaela** [urbandroid-team/dont-kill-my-app#21]
The closest in app settings I can see is "Akun säästäminen" (Battery saving), but it's already stopped. When I try to use adb, I receive:

```
FRT:/ $  pm uninstall --user 0 com.evenwell.powersaving.g3
Failure [not installed for 0]
```

Attempting to look for similar packages, I find

```
FRT:/ $ pm list packages|grep com.evenwell.powersaving
package:com.evenwell.powersaving.g3.overlay.base.s600ww
```

However I don't know if this is the package I should remove and am a bit afraid of removing it by myself, so I am still googling for `com.evenwell.powersaving.g3.overlay.base.s600ww`. Nokia 1 is an Android Go device which may be the reason for different package assuming the page has been written with Android One or their customized Android in mind.

* * * * *

8 minutes later:

```
pm list packages|grep com.evenwell.battery
package:com.evenwell.batteryprotect.overlay.base.s600ww
package:com.evenwell.batteryprotect
```

So far these packages are listed as something requiring more testing, but [Robert Wallis at Medium says to have removed them without problems](https://medium.com/@robert.wallis/bloatware-crapware-on-nokia-mobile-x-1-phones-really-c483ff5eca3), but their phone doesn't seem to be Android Go.

**Comment by Mikaela** [comment]
I ended up uninstalling all the mentioned packages as while there are mixed comments on whether it fixes the issue, everyone agrees that it didn't cause any problems so I will be seeing if anything changes.

When I first got this device, I assumed this was Android Go specific oddity, which I guess it can still be.

**Comment by namandixit** [comment]
@mikaela On Nokia 1, the app that should be removed is `com.evenwell.emm`. I have personally tested this and removing this package seems to completely disable the battery optimizations; i.e., apps keeps crowding the RAM until the kernel decides to clean memory and "swaps" those processes.

While this is not ideal, I have not found a better solution - lesser of the two evils, I suppose.

**Comment by Artaud** [comment]
This is very interesting and should be added to the website. Thanks a lot.

@namandixit do you know if this package name is present also on other Nokia phones?

**Comment by namandixit** [comment]
@Artaud I think it is also available on Nokia 2 (atleast [this XDA post](https://forum.xda-developers.com/general/general/nokia-2-apps-safe-to-delete-t3783158) refers to it). I do not know whether or not it performs the same function.

**Comment by Mikaela** [comment]
Thank you, I removed it from my phone and will close this in favour of your cleaner https://github.com/urbandroid-team/dont-kill-my-app/issues/25.
