### ISSUE TITLE
Tecno and Infinix

### ISSUE THREAD

**Issue by githinji84** [urbandroid-team/dont-kill-my-app#213]
Hi,

Thank you for pushing this agenda. Have you been able to add more manufacturers? I am specifically looking for Tecno and Infinix. I am building an app in Africa and they are the biggest OEMs here. like 70% of my user base can not receive notifications.

If not, do you have any ideas on how to get the intent I need to call for this 2 OEMs. i have searched for contacts to their developer support and i don't think it exists.

Please let me know if you can help.

Regards
Simon

**Comment by hiranurbahceli-ux** [comment]
Liseli

[Legal_Notice.txt](https://github.com/user-attachments/files/29057201/Legal_Notice.txt)
