### ISSUE TITLE
Samsung developer instructions

### ISSUE THREAD

**Issue by Somethingweirdhere** [urbandroid-team/dont-kill-my-app#22]
Not sure if this will always help, but there is one thing developers can sometimes do against the optimization it seems:

https://seap.samsung.com/api-references/android-standard/reference/android/app/enterprise/ApplicationPolicy.html#addPackageToBatteryOptimizationWhiteList(com.sec.enterprise.AppIdentity)

Should we add it?

**Comment by Artaud** [comment]
Thank you.

This method seems to need a special signature level permission, which is, by definition:

`A permission that the system grants only if the requesting application is signed with the same certificate as the application that declared the permission. If the certificates match, the system automatically grants the permission without notifying the user or asking for the user's explicit approval.`

The permission needed is **android.permission.sec.MDM_APP_MGMT**, but to use it, you need to be enrolled in SEAP and have your app signed by Samsung.

This is something only corporate developers would be able to use, isn't it? I believe the audience of the website is indie developers and end users, so if you don't mind, I'd keep it here on Github but wouldn't add it to the main content.
