### ISSUE TITLE
Feedback for OnePlus page

### ISSUE THREAD

**Issue by omair94** [urbandroid-team/dont-kill-my-app#221]
Information is outdated. On newer versions of Android, Oxygen OS no longer has a "Deep optimization" setting or a "recent app management" option.

**Comment by petrnalevka** [comment]
Hello, many thanks. Unfortunately, we cannot do much, we rely on volunteers on the community to report new workarounds and provide new screenshots for new versions of Oxygen OS..

**Comment by R0tten** [comment]
> Hello, many thanks. Unfortunately, we cannot do much, we rely on volunteers on the community to report new workarounds and provide new screenshots for new versions of Oxygen OS..

How can we provide workarounds and new screenshots?

**Comment by petrnalevka** [comment]
Teh whole website is open source so ideally you submit a pull request, or if that is too demanding you can post a descriptions and screenshots here into the issue tracker and we will add them in our free time..
