### ISSUE TITLE
Feedback for Huawei page

### ISSUE THREAD

**Issue by GoldGuy64-GD** [urbandroid-team/dont-kill-my-app#223]
I'm using an EMUI 4 mobile (Huawei Y5 Lite) and I don't know how to stop app killing on it. Try searching and adding it.

**Comment by Artaud** [comment]
Hi, we rely on volunteers for all the information as we do not have access to every phone. All information that we have at hand is on the website. It would be tremendously helpful if you could try some of the steps outlined at the Huawei page (it's been updated since) and let us know.
