### ISSUE TITLE
Feedback for Nokia page

### ISSUE THREAD

**Issue by tagauch1** [urbandroid-team/dont-kill-my-app#224]
its not just 
adb shell settings put global setting.duraspeed.enabled 0
you also need
adb shell settings put system setting.duraspeed.enabled 0

I think the system setting is the default for the boot receiver

I decompiled the code of duraspeed and found:
public static void setDuraSpeedStatus(Context context, boolean isEnable) {
        System.putInt(context.getContentResolver(), "setting.duraspeed.enabled", isEnable);
        Global.putInt(context.getContentResolver(), "setting.duraspeed.enabled", isEnable);
}

and this is called from the DuraSpeedMainActivity / DuraSpeedFragment when clicking the switch to activate/deactivate.
DuraSpeedMainActivity is not accessible on every device, because it has no launcher and manufactures need to add this to their settings page.

**Comment by Artaud** [comment]
Big thanks! Added in commit 28494d056af62892b4b459df400c7af743ec5825
