### ISSUE TITLE
Possible solution for disabling powergenie on EMUI 5

### ISSUE THREAD

**Issue by sandorex** [urbandroid-team/dont-kill-my-app#225]
I have been fiddling around to disable powergenie for a while and found a possible solution, it has not been thoroughly tested so i don't know if there are some problems caused by it

My device is HUAWEI P9 Lite 2016

How i disabled it:
```
pm uninstall -k --user 0 com.huawei.powergenie
pm uninstall -k --user 0 com.huawei.android.hwaps
```

I haven't noticed any problems after doing this, and doing `pgrep powergenie` returned nothing

If apps keep getting killed try running `pm stopservice hwPfwService`

**Comment by sandorex** [comment]
My phone has been running for ~4 days like this and i haven't seen apps get killed, i've not found anything broken as of writing this

**Comment by Artaud** [comment]
Thanks a lot, I've added this information in commit e964c63eecd29c5888d483692eb1ba9e070c6c8e

**Comment by sandorex** [comment]
Could you mention this in EMUI 5 section too? cause it currently looks like it's EMUI 9 only
