### ISSUE TITLE
Feedback for Xiaomi page

### ISSUE THREAD

**Issue by mfuentescas** [urbandroid-team/dont-kill-my-app#230]
**MIUI 11 / App settings**
To let your app run successfully in the background, make sure your app settings look like the following (here for example is "YOUR APP"):

![disable_miui_baterry_saver_1](https://user-images.githubusercontent.com/12676983/91563045-82355980-e93e-11ea-9377-c0b7132cd530.png)![disable_miui_baterry_saver_2](https://user-images.githubusercontent.com/12676983/91563053-8497b380-e93e-11ea-9c74-aa2709ecb8af.png)

Tested on Xiaomi Redmi Note 9 Pro / Android 10 / MIUI 11.0.3.

**Comment by petrnalevka** [comment]
Big thanks for sharing this.. we will include it in the DKMA guide and just now asking for feedback if others can confirm this fixes the issues..

**Comment by Artaud** [comment]
Added to Xiaomi guide with commits dc24fa4609b9c6a48e418c75f02900cf82b1cd2a and 12e8f04008ef2de46b1bfb885a49986f1012349d
