### ISSUE TITLE
What is "stock Android"? 

### ISSUE THREAD

**Issue by Madis0** [urbandroid-team/dont-kill-my-app#24]
Surely it must be easy to compare to stock Android in the sense of AOSP, but that is not easy for consumers to grasp. 

I would suggest some names, for example: 
- Nexus
- Pixel 
- Nextbit 
- Essential 
- Razer 
- Android One (Xiaomi? any? Nokia probably messed that up)

**Comment by Artaud** [comment]
I understand completely. I've removed the Stock Android option and called it properly after what is meant by that: Google (Pixel, Nexus) to avoid confusion with regards to AOSP or Android One program.

Closed with 568052ad2771bacfe330a19d2ef6c2e9a45b543e
