### ISSUE TITLE
Nokia 1: Different package, same BS

### ISSUE THREAD

**Issue by namandixit** [urbandroid-team/dont-kill-my-app#25]
On Nokia 1, the package that should be disabled is `com.evenwell.emm`. Removing it seems to completely disable any battery/memory optimizations that Android might make, thus resulting in apps slowly filling the memory. Once enough memory has been filled, the kernel apparently kills or evicts the background processes. 

Disabling the `Battery Optimizations` of an app in `Settings` keep the app memory resident forever. Manually swiping away the apps from the `Recent Apps` list when done with them seems to keep the phone running smoothly without any hitches. 

Disabling `Battery Optimizations` of apps that are supppsed to run in background and manually closing any unused apps seems to be the best way of using this device for now.

**Comment by Artaud** [comment]
I'm adding that to the Nokia entry. Big thanks!

**Comment by Artaud** [comment]
Closing with 5cc66aea64fd536a9b91abd973d06c8ef1627e05

**Comment by Mikaela** [comment]
I wonder if there should also be restoration instructions somewhere just in case?

[Wazakindjes at XDA-forums](https://forum.xda-developers.com/showpost.php?s=67857b61a71e1f45cd7340b2dd81f9b9&p=77318240&postcount=10) has a solution of finding and reinstalling the apk with (optimized for my phone, untested as I don't want to restore that package):

* `find /system -iname "*emm*"`
* `pm install --user 0 -r /system/app/emm/emm.apk` 

(pinging #21 even if I don't know if there is any point)
