### ISSUE TITLE
Feedback for Huawei page

### ISSUE THREAD

**Issue by karimdjelid** [urbandroid-team/dont-kill-my-app#258]
There's one additional step for users of EMUI 9 to prevent the OS from killing an app in the background.
Together with the first step you describe, this usually works.

2nd step is described here:
https://consumer.huawei.com/en/support/content/en-us00428704/

 "Disable battery optimization functions:
EMUI 5.X and EMUI 8.X: Open Settings, and search for and access Ignore battery optimization. Touch the little inverted triangle next to Allow, touch All apps, locate and touch the app, and select Allow.
EMUI 9.X and later: Open Settings, and search for and access Battery optimization. Touch the little inverted triangle next to Don't allow, touch All apps, locate and touch the app, and select Don't allow."

Hope that helps others. And me next time I forget about it again :)

**Comment by Artaud** [comment]
Added, big thanks!
