### ISSUE TITLE
Notice of an additional power saving app for Nokia devices

### ISSUE THREAD

**Issue by friendlyfredward** [urbandroid-team/dont-kill-my-app#290]
Nokia 2 owner here - I noticed that there's a new package name and battery protection app that isn't listed in the dontkillmyapp.com/nokia page.

The new package name is `com.evenwell.batteryprotect` and it can be disabled just like the other apps with `pm disable-user com.evenwell.batteryprotect` in adb shell. Just providing feedback so it may be added to the page!

**Comment by Artaud** [comment]
This package is a genuine battery protection app that kicks in when the battery is overheating. This app is AFAIK harmless regarding app killing.
