### ISSUE TITLE
Feedback for Samsung page

### ISSUE THREAD

**Issue by sebouh00** [urbandroid-team/dont-kill-my-app#294]
In recent updates, Samsung has introduced stricter rules for app background execution. Apart from the "sleeping apps" feature, which comes into effect after a few days, this new change is more immediate and similarly restrictive. The only way to circumvent it is by disabling Android's "app battery optimization."

Please see https://issuetracker.google.com/issues/179644471

**Comment by petrnalevka** [comment]
Hello @sebouh00, big thanks for sharing this. This really sounds scary. 

I have read through your post on the Android issue tracked and starred it. So far we do not have this issue reported in most cases removing the app from sleeping apps fixes the issue. But I guess Android 11 just started to roll out on Samsung so we may see more such issues coming.  

I'm also very much dissapointed that the promise from the Android team to enforce a user facing warning when activating non-standard battery optimizations on apps has gone in vain :(.. 

Personally I'm voting for putting Samsung on the top most position on the DKMA website even before 1+ which is really terrible. But the direction into even stricter app killing in a situation when the sleeping apps "feature" is already causing so much harm does not leave us with other options IMHO.. 

Big thanks for sharing this will update the doc with Android 11 section on the Samsung page..

**Comment by petrnalevka** [comment]
@sebouh00 forgot to ask. Could you please share some screenshots of enabling the Battery optimization setting - I guess Samsung did heavily modified the screens so screenshots from my Pixel would not be that useful? Big thanks..

**Comment by sebouh00** [comment]
[Here](https://drive.google.com/file/d/1eQ0A51VXUrZOv9iU3mcgSezoIf0J0Usx/view?usp=sharing) are the screenshots. The steps are: Settings > Apps > [App Name] > Battery > Optimize battery usage > All (from the top) > [App Name] (toggle to disable).

**Comment by petrnalevka** [comment]
Big thanks for sharing this I did request access to the screenshots..

**Comment by petrnalevka** [comment]
We have updates https://dontkillmyapp.com/samsung accrodingly and Samsung is now #1 in the list.. big thanks for sharing all the details..
