### ISSUE TITLE
<a href="https://dontkillmyapp.com/vivo"><img id="badge-shareable" width="306px" src="https://dontkillmyapp.com/badge/vivo3.svg"></a>

### ISSUE THREAD

**Issue by Thanasak-Sompong** [urbandroid-team/dont-kill-my-app#295]

**Comment by petrnalevka** [comment]
Hello, what is the issue? I see the batch propery?

**Comment by Bobrik8272** [comment]
<a href="https://dontkillmyapp.com/tecno"><img id="badge-shareable" width="306px" src="https://dontkillmyapp.com/badge/tecno3.svg"></a>

**Comment by Bobrik8272** [comment]
<a href="https://dontkillmyapp.com/tecno"><img id="badge-shareable" width="306px" src="https://dontkillmyapp.com/badge/tecno3.svg"></a>
