### ISSUE TITLE
Feedback for Vivo page

### ISSUE THREAD

**Issue by Xi-PP** [urbandroid-team/dont-kill-my-app#311]
VIVO Y11 new Update to Android 11 doesn't kill Apps if you close it from recents. Even if you enable Ultra Game Mode app will not Forced Stop.

**Comment by petrnalevka** [comment]
This is great news.. at least some vendors are easing restrictions?

**Comment by Xi-PP** [comment]
Yeah & other apps working normally when I recieve any notification. No need to disable per app battery optimization for notifications.
