### ISSUE TITLE
Request for clarification: Does using a foreground service protect the app?

### ISSUE THREAD

**Issue by sandebert** [urbandroid-team/dont-kill-my-app#32]
The recommended way to run tasks in the background is with foreground services. I'd like a clarification if doing so would protect the app from getting killed?

If it does protect the app, wouldn't it make sense to add that to the _Developer workaround_ section?

**Comment by ol-v-er** [comment]
We've tried this solution in our app, unfortunately with no luck. It does not prevent crappy manufacturer customization to kill the apps. For sure it's a bit better, but does not last more than one hour or 1 day...

It's in fact the main goal of this project : the official Android documentation describe multiple solutions to keep our app alive and run our process (foreground service, task manager...) but it only works on stock Android. The manufacturers listed in the dont-kill-my-app project breaks the stock and documented behaviour.

**Comment by Artaud** [comment]
Exactly as @ol-v-er said.

**Comment by sandebert** [comment]
> It's in fact the main goal of this project : the official Android documentation describe multiple solutions to keep our app alive and run our process (foreground service, task manager...) but it only works on stock Android. The manufacturers listed in the dont-kill-my-app project breaks the stock and documented behaviour.

In that case it might be good to also, on each page, list the ways that are recommended by Google, and whether or not that works for the device. It would be a way of clarifying how much the vendors are going against Googles own recommendations.

**Comment by Mikaela** [comment]
On my Nokia 1 even accessibility services kept getting killed until I removed the `com.evenwell.emm` package and they lost the accessibility permission for force stop. I am using Bitwarden (with persistent notification for least battery drain for apps not supporting autofill), SuperFreezZ and YACO Overlay.

**Comment by r10s** [comment]
thanks for the information, although these are not really great news.

in fact, with Delta Chat we're currently also switching to a foreground notification, see https://github.com/deltachat/deltachat-android/pull/1302 - even if it does not solve all problems directly: if the notification is _missing_ it is a clear hint to the user that things won't work any longer and some settings have to be tweaked (we point them to https://dontkillmyapp.com for details :)
