### ISSUE TITLE
Feedback for Samsung page

### ISSUE THREAD

**Issue by rubnov** [urbandroid-team/dont-kill-my-app#343]
We are forwarding users from our Android app to `https://dontkillmyapp.com/{manufacturer}`, based on the manufacturer of the user's device. 

It would be really nice if you could add an anchor at the "solutions for users" header on each of the manufacturer-pages, so that users can land directly in the relevant section, where the screenshots from Android Settings are displayed.  

thanks!

**Comment by Artaud** [comment]
Hi, you can already use https://dontkillmyapp.com/{manufacturer}#user-solution-section
