### ISSUE TITLE
Feedback for Huawei page

### ISSUE THREAD

**Issue by washurpaws** [urbandroid-team/dont-kill-my-app#347]
Hi, I'm not sure if I'm doing this right.. but I noticed running `adb shell pm stopservice hwPfwService` doesn't work, ADB doesn't detect it as a command. `adb shell pm uninstall -k --user 0 com.huawei.powergenie` and `adb shell pm uninstall -k --user 0 com.huawei.android.hwaps` work just fine, but i can't figure out how I'm supposed to use that last one. Thought I'd report that, although there's a high chance I just did something wrong.

EDIT: After googling a bit more, I found the command `.\adb shell am stop-service hwPfwService` works without an issue... except there isn't a service called that. Weird, let's hope my apps work now :p

**Comment by kyoforkshomebrews** [comment]
yeah, i think it's supposed to be `adb shell am stopservice hwPfwService`

**Comment by rl885** [comment]
Hi, big sorry this was not updated sooner - the thread was lost and I only found it when one user pointed that out to me.
It should be corrected by now.
Thank you so much for your help!
