### ISSUE TITLE
Add Lenovo

### ISSUE THREAD

**Issue by mrquincle** [urbandroid-team/dont-kill-my-app#36]
The Lenovo P2 has a very good battery life, but it's at a cost.

For an app to work in the "background" you have to enable the padlock icon at an app in the right top corner in the overview of running apps. It's actually then running as a foreground process. If you swipe it away, its background process will be killed mercilessly.

It does not matter if in settings -> apps, the battery/power optimization is on or not.

> All being said, in general I recommend the phone nevertheless.

**Comment by Artaud** [comment]
Big thanks! Added in e11533ecb0914dfd0b53b8214c9f95fd2e8a5a4a
