### ISSUE TITLE
Feedback for Vivo page

### ISSUE THREAD

**Issue by jmorgannz** [urbandroid-team/dont-kill-my-app#363]
Hi,

These fixes no longer work on Vivo Y70 (V2023)
Previously locking the app in the task manager appeared to work quite consistently; however this has since stopped working - seemingly since a system update but can't be sure on that.  

Android: 11
ROM version: Funtouch OS 11 Global, PD2038BF_EX_A_36.8.20

**Comment by petrnalevka** [comment]
Many thanks for reporting, can you double check? We will wait for confirmation and worsen Vivo score accordingly, but we need to wait for someone to propose some guide, we do not have any Vivo phones here..

**Comment by jmorgannz** [comment]
Well it has done it to be three times since the update.
My apps are pinned and autostart is allowed.

I keep three apps open all night - NotifyMI for my MI band, Sleep As
Android for realtime tracking, and music player playing rain.
Since update I keep waking up and music player is dead, no more rain sound;
and also Sleep As Android has been killed so my sleep data is incomplete.

Do I need to run the DKMA app to confirm?

Cheers
Jesse
