### ISSUE TITLE
Sony rating

### ISSUE THREAD

**Issue by blassepl** [urbandroid-team/dont-kill-my-app#38]
I'm very long time Sony user and I'm not sure if the rating for Sony is justified. Stamina mode is turned on manually (or automatically on low battery if you set up itthat way), but upon enabling it clearly describes that it will break background process.
I cannot agree with ranking in-pair with Huawei or Meizu, where you are almost not able to prevent killing apps and phone is even not informing you about such policy. With Xperia line user is in control. You want background processes - you don't use stamina. You enable stamina - phone is alerting you: "are you sure? You will get some juice, but you will break apps in background. Do it wisely.". It's rather example to follow!

**Comment by Artaud** [comment]
Big thanks for bringing this up. I'm not sure if this was always the case. We based the rating on the rather historical fact that Sony was one of the first, if not the first at all to create a vendor modification to save battery. We had our fair share of issues indicating that users did not know what the Stamina mode was actually doing at that time.
But if what you say is now their policy, then they sirely don't deserve a bad rating.

**Comment by petrnalevka** [comment]
Many thanks for the update. I can confirm that in production we are also getting minimum complains from Sony users, this is absolutely uncomparable to Nokia, 1+, Xiaomi or Huawei..

So we did update the score accordingly..
