### ISSUE TITLE
Feedback for Wiko page, Wiko Power U10

### ISSUE THREAD

**Issue by arkanoid87** [urbandroid-team/dont-kill-my-app#418]
I have Wiko Power U10 and `Phone Assistant` does not have any `Advanced` or `battery` settings, also dialing`*#*#86569726#*#*` doesn't do anything (just clears the dialing screen confirming that the action is triggering something)

**Comment by arkanoid87** [comment]
Found something:

- Battery >
  - POWER SAVING OPTIMIZATION >
    - Power Saving `disable`
    - Battery Manager > User Battery Manager `disable`
  - APPS BATTERY SETTINGS:
    - Apps optimization `select app`:
      - App optimized `disable`
      - Standby wakeup optimization `No optimize`
      - Standby sleep optimization `No optimize`
      - Standby network data `No optimize`
    - Close apps after screen lock `disable on selected app`
    - Auto launch management:
      - App auto launch `enable on selected app`
      - App secondary launch `enable on selected app`

`BOOT_COMPLETED` action does work now, testing killing on standby

**Comment by rl885** [comment]
Hello, would it be possible to send me screenshots of these settings? I will update the page for the Wiko - some users visiting the project web can have troubles with English, so seeing the layout on images will help them recognize the corresponding option in their system settings. Thanks.

**Comment by arkanoid87** [comment]
> Hello, would it be possible to send me screenshots of these settings? I will update the page for the Wiko - some users visiting the project web can have troubles with English, so seeing the layout on images will help them recognize the corresponding option in their system settings. Thanks.

I understand.
Once I can confirm that the solution I've found fully works as intended, I'll produce screenshots.
I've only confirmed that the BOOT_COMPLETED is triggered and the service starts at boot, but I've yet to prove it keeps running endlessly.
