### ISSUE TITLE
Question: get official comment/direction from the manufacturers

### ISSUE THREAD

**Issue by oferRounds** [urbandroid-team/dont-kill-my-app#42]
Great website and initiative! Way to go for this!

Do you think it might be a good idea to try and send this website/relevant section for each manufacturer, and get their words on the subject?

**Comment by Artaud** [comment]
Definitely.

We have been already contacted by OnePlus who saw the website and tried to explain their motivation.
We did not contact anyone by ourselves, and noone else contacted us, although I've seen the website link being tweeted to Juho Sarvikas of Nokia.

**Comment by oferRounds** [comment]
Great! What did the people from OnePlus said (if I may ask)?

I think it’s also worth sending it from your side (to the other manufacturers), if they don’t approach by themself

**Comment by oferRounds** [comment]
Cool :)
But do they have any suggestion of what can be done developer-wise?

**Comment by oferRounds** [comment]
@Artaud any solution for OnePlus? Sorry for bugging, asking again as this is one of our most problematic devices (i.e., the one we get most complaints about), regarding our geofencing foreground service

**Comment by petrnalevka** [comment]
@oferRounds Hello, all we know we try to publish to the site. So in fact https://dontkillmyapp.com/oneplus is all we know at the moment. I guess geofancing put another level of issues on top of background processing and even in stock Android GPS gets restricted on the background. But we do not have geofancing apps in use so we do not have direct feedback on that..
