### ISSUE TITLE
Request: Please include link to Google's issue tracker about this issue

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [urbandroid-team/dont-kill-my-app#46]
Here:
https://issuetracker.google.com/issues/122098785

It talks a lot about the issues that (mainly Chinese) manufacturers cause...

**Comment by yccheok** [comment]
Thanks for sharing this. At least we know Google has been informed officially. I think if thing goes out of control, Google will try to pull back battery optimization policy from phone device OEM, back to Google own hand. 

This is more preferable way, so that we, developers only need to write code according to Google's specification, and not phone device OEM's specification.

May all Alarm app in Google Play store work flawless again! (Including Google own Alarm app)

**Comment by AndroidDeveloperLB** [comment]
Why the downvote? :(
Also, I suggest to star this issue, to raise awareness

**Comment by ocram** [comment]
That specific issue does *not* seem to be a generic and comprehensive thread for the problems of “battery optimization”. It just seems to be yet another attempt at getting Google or the vendors to listen. Besides, it doesn’t have much information provided by Google. Mostly it’s inquiries from users and developers about things we know and which this project already describes.

**Comment by AndroidDeveloperLB** [comment]
@ocram Incorrect. It is all about what Chinese companies are doing. This includes battery optimization settings, killing apps, not allowing apps to "auto-start" themselves (which is just Intent handling),...
When I wrote about these crucial changes, it was marked as duplicate:

https://issuetracker.google.com/issues/123653024

They cover there all kinds of dangerous changes ...

**Comment by Artaud** [comment]
I think it might be useful to link it somewhere so more people can find and upvote the issue.
However all of the issues are most probably not addressable by Google. I'm not an expert on how the Android certifying process works, but for example Nokia does this by preinstalling a system app. While certainly undesirable (coupled with the fact that you can't disable or uninstall the app easily), it is questionable whether this is modifying the Android system in a way that might violate certification policies.

I'd love to be enlightened with regards on how the certification process works.

And regarding the link - where should it be put? I'm hesitant to snap it to any vendor..

**Comment by AndroidDeveloperLB** [comment]
@Artaud That's what I did. It's should be Google that will impose those rules on the licensing, so that companies won't add behaviors that break apps by default. This website of "don't kill my app" just proves how important it is. And it shows just one aspect of it...
I don't know how they got away with this, but they ruin the eco-system. They ruin apps, and they ruin the experience to users, by default.
I want Google to do something about it. That's why I think this website should join the battle against this behavior (in all kinds of those issues). 
About where to put the link, you can start by writing it on the "our mission" page, and also add the link of "contribute" or "help fight this" or something like that, both on the main page and on the "our mission" page (yet there it could be with a sub-title and paragraph, with explanation of what's going on, including other bad behaviors).

**Comment by Artaud** [comment]
Closing with 1be6b9ce28bc9494063af52a3f7601671be57358

**Comment by AndroidDeveloperLB** [comment]
Yes, I see it here:
https://dontkillmyapp.com/problem
Right?

**Comment by Artaud** [comment]
Yes, that's it!

**Comment by AndroidDeveloperLB** [comment]
OK thank you.
Do you have any news about Google though (related to this) ?
They haven't responded recently on those threads...
