### ISSUE TITLE
Add Wiko and Asus

### ISSUE THREAD

**Issue by Artaud** [urbandroid-team/dont-kill-my-app#47]
Add those vendors from https://baviux.com/ladypillreminder/troubleshooting/
Permission already granted.

**Comment by hb0** [comment]
A user with a "Wiko View Prime (v12bn)" reported tracking issues, which could be related.

**Comment by petrnalevka** [comment]
Please correct me IMHO for Wiko, we can use the general advice for Wiko:
https://dontkillmyapp.com/general

For ASUS I did add an entry:
https://dontkillmyapp.com/asus
