### ISSUE TITLE
Information to add for Infinix and Tecno phones

### ISSUE THREAD

**Issue by ghost** [urbandroid-team/dont-kill-my-app#474]
Hello! I wanna add in to dkma for Infinix and Tecno devices, because it just kills apps in the background and having notifications delayed. I'm also new to GitHub so hehe...

(I'm using a Infinix Hot 10 Play running Android 11 May 5 2022 Android Security Update)

Open "Power Marathon"
 -> Power Boost = OFF 
• Smart Scenes 
 -> Short Video Optimization = OFF
(I think its for apps like TikTok)

 -> Sleep Mode Optimization = OFF (Optional)
(Turns on airplane mode at night when you're not using the phone)

• Advanced Settings
 -> Power Boost Reminder = OFF (Optional)
 -> Screen off push block = OFF
 -> Screen off sleep = OFF
 -> Screen off scheduled push = OFF
 -> Battery Optimization = Basically yeah...
 -> Battery Saver = OFF

Open "Phone Master" 
 • App Booster = Add in your messaging apps, email apps, apps that runs in the background like AccuBattery or in startup like launchers. You can only put 4 apps
 • Auto-start Management = Enable all of them :) 

![Auto-Start Management All Enabled](https://user-images.githubusercontent.com/107795246/175885156-7e9dd885-9d87-480d-b3db-12a02d8e3c7b.jpg)
![Phone Master App Booster with Added Apps](https://user-images.githubusercontent.com/107795246/175885171-3d107687-04d7-4c55-8562-38d857d43fe7.jpg)
![Phone Master Scrolled Down_1](https://user-images.githubusercontent.com/107795246/175885185-c367ff06-923a-457e-8140-352667268834.jpg)
![Power Boost Reminder](https://user-images.githubusercontent.com/107795246/175885186-5e1fc898-3fa9-4fae-8e9a-e812310b6c42.jpg)
![Power Marathon Advanced Settings](https://user-images.githubusercontent.com/107795246/175885194-47822745-27aa-4abe-a1dd-9adeabf0bbdb.jpg)
![Power Marathon and Phone Master on Lawnchair Folder](https://user-images.githubusercontent.com/107795246/175885198-ea9fef20-e447-4df9-aca7-fe721236c977.jpg)
![Power Marathon Main Screen](https://user-images.githubusercontent.com/107795246/175885208-7ef705b4-ab64-463b-acec-be30ad0f9106.jpg)
![Power Marathon Smart Scenes](https://user-images.githubusercontent.com/107795246/175885216-a190a53c-3c07-4869-9768-f9e0cd4dcf17.jpg)
![Screen Off Push Block Turned Off](https://user-images.githubusercontent.com/107795246/175885225-b76e387c-d7e2-4a7f-9c91-9558606bb194.jpg)
![Screen off scheduled push turned off](https://user-images.githubusercontent.com/107795246/175885226-f5cae780-bed8-460a-a447-c2d91390183d.jpg)
![Screen off sleep turned off](https://user-images.githubusercontent.com/107795246/175885232-30aa331c-9ab1-46d0-a197-7da0842d90a3.jpg)
![Sleep mode optimization turned off](https://user-images.githubusercontent.com/107795246/175885238-fcfe5786-0027-40de-8429-6732c388fc65.jpg)

**Comment by kyoyacchi** [comment]
Thanks for this information.  I was wondering what makes Tachiyomi force stop in my device.

May I ask what launcher you're using?
