### ISSUE TITLE
Add Oppo

### ISSUE THREAD

**Issue by fennifith** [urbandroid-team/dont-kill-my-app#51]
I have only done minimal research as of yet, but Oppo seems to be quite notorious for _not allowing any services to run in the background when the screen is turned off_, and I believe it would be a worthy addition to this site.

The only situation that I can personally point to is with the Oppo F1S, I encountered a user for which my app's background services were killed (including accessibility services, which needed re-enabling) every time they turned the screen off. So far, a workaround for this is:

- pinning the app to the recent apps screen
- enabling it in the app list inside the security app's "startup manager" and "floating app list" (`com.coloros.safecenter / com.coloros.safecenter.permission.Permission`)
- turn off battery optimizations
- give the service a persistent notification to remain in the foreground

All four of those needed to be done before the app would function. Here are links to some other resources verifying that some of the above steps work on other Oppo devices:

https://forum.xda-developers.com/android/general/coloros-5-0-how-to-allow-apps-running-t3847738
https://forum.xda-developers.com/find-X/help/killing-apps-screen-off-arghh-t3818105
https://oppo-au.custhelp.com/app/answers/detail/a_id/1313/~/how-to-lock-applications-in-the-background%3F
https://www.quora.com/How-do-you-add-apps-into-Whitelist-in-OPPO-F1s-phone

Hopefully I will have the time to contribute to this project more - I hope to start organizing my own records of background service-related problems on various devices sometime soon, and will gladly merge the information I find with this project if it is of use.

**Comment by petrnalevka** [comment]
Hello, I can confirm we have a lot of OPPO issues reported from our apps. But as there are not so many devices out there we have minimum feadback from users on how to overcome the issues. 

So many thanks for posting the details. I guess we can start with that as a base and build on that later on..

**Comment by adityadroid** [comment]
@fennifith , As of Color OS 6 the "Auto Start" setting has moved to the App Info Page, Startup Manager app is not there on COS 6. 
![photo_2019-08-08_22-06-21](https://user-images.githubusercontent.com/17155247/62720968-cf3f4880-ba28-11e9-9485-9e1507b7599b.jpg)

**Comment by AniG007** [comment]
You can also click on the power saving option under each app and allow the app to run in background. If something like smart restriction is enabled, if the app is not cleared from the tasks, it should be running background processes but it the app is closed, the background services resume immediately when the app is opened again.

**Comment by AliNetteam** [comment]
Hi, 

my app doesn't work on Oppo A31 with Android 9 and ColorOS 6.1. App gets location and sends it to server. If I screen off, app works only 5 minutes and then stops. I use Handler and AlarmManager and Foreground Service with Notification to handle background work. App works correctly on Huawei, Samsung, Sony and Xiaomi phones. 

I turned off battery optimization by permission in app.

I have in Settings -> Battery: 
- Power save mode off,
- Intelligent protection for use energy off,
- Not standard energy save -> my app -> Run in backgroound,
- Energy save options -> Optimisation while sleep off.

In Settings -> App management -> my app -> Auttostart I have on.

I tried to lock and pin app. Still the same problem. 

Do you have any ideas to resolve my problem?
