### ISSUE TITLE
Miui 19 Pie-edition

### ISSUE THREAD

**Issue by Melker63** [urbandroid-team/dont-kill-my-app#53]
Consider changing Xiaomi Miui 10 Pie-edition from 3 to 4 thumbs down. Suggested or equivalent changes in Settings don't work reliably anymore. Also, the Settings-structure have changed with Miui 10 Pie-edition, so the suggested step-by-step guide doesn't apply anymore. Finally: point out that a Xiaomi-phones with Google Android One system installed (like Xiaomi A2 Lite) works much better and should be given a rating of only 2 thumbs down.

**Comment by petrnalevka** [comment]
Hello, many thanks for the update. I suggest we will gather more feeedback on the MIUI 10 first to get this verified from more sources to mitigate the change this is some device specific bug for instance..

Would you please provide a new guide for MIUI 10 for us? Ideally as a pull request or just in plain text and we will include it.. if you have a screenshot that would be great!

I'm not sure how to handle Android One yet, I guess this is a special category, it cannot be covered in the Pixel / Stock section as OEMs like Nokia still put the most severe task killers on Android One, so maybe we could have a special section for each AO vendor I guess..

**Comment by alx2000** [comment]
I'd would like to aid, but I didn't found all settings on Xiaomi Android 9 Miui 10.2 and my apps are being killed. Layout is so different in this version... :-(

**Comment by petrnalevka** [comment]
Many thanks, I did update the section about Android One and we are waiting for someone to provide new screenshots for MIUI 10.. so far I'm closing this issue..
