### ISSUE TITLE
People 

### ISSUE THREAD

**Issue by riadsaef** [urbandroid-team/dont-kill-my-app#542]
6#538 
Whtssapp
0544753155

- [x] bybwwl2019/:snapshot/:_{

**Comment by riadsaef** [comment]
> 6#538 Whtssapp 0544753155
> 
> * [x]  bybwwl2019/:snapshot/:_{

**Comment by GMANNMODS** [comment]
STOP FUCKING EMAILING ME!!!

**Comment by riadsaef** [comment]
Dear, send the link to the mobile phone, sorry
