### ISSUE TITLE
351F-B04 update for Nokia SDM63x/660 devices seems disabled Power Saver G3 by default

### ISSUE THREAD

**Issue by HikariCalyx** [urbandroid-team/dont-kill-my-app#55]
Recently HMD pushed 351F update (March 2019) for Nokia 6.1/6.1Plus/7.1/7Plus and disabled Power Saver G3 from system, although they didn't remove it.

Power Saver G3 was originally designed for handling Chinese bloatwares, such as WeChat, Alipay, Taobao, TikTok, Kuaishou, etc. China variant uses "Whitelist" policy instead of "Blacklist". For some reason, looks like they didn't realize Power Saver G3 is unnecessary for Global release until now. Power Saver G3 will always exist in China Variant Nokia Phones.

Following URLs are Full OTA for both Nokia 6.1 and Nokia 7 Plus Global, if you want to analyze:

https://android.googleapis.com/packages/ota-api/nokia_pl2sprout_plate200ww/3601a351ff7577ed5a013d6f4fe5fdd64d32355c.zip

https://android.googleapis.com/packages/ota-api/nokia_b2nsprout_onyx00ww/5255f45225061bdc1c3525a32cf7361480e45ea3.zip

If you want to know your current Firmware Build, you can either dial * # * #227 # * # * to check "Version" in BBox app, or use command "fastboot oem getversions" under Fastboot/Download mode if BBox app displays nothing.
Expected build version looks like this: B2N-351F-0-00WW-B04, which is stored at systeminfo partition or /proc/fver .

**Comment by petrnalevka** [comment]
Incredible, big thanks for sharing this! We will check the resources and hopefully test the update soon on the Nokia 6.1 we have around @Artaud

**Comment by IvanFrederiks** [comment]
I installed the update, but know power saver apps are not disabled. Maybe their behavior was changed? @petrnalevka, is there any way to test it?

**Comment by petrnalevka** [comment]
@IvanFrederiks good question. In Sleep as Andoid we already have a screen always on hack for Nokia.. so it is not that easy, maybe we could prepare a test case APK but I do not have the time now.. 

It could be tested with one of the older APKs of Sleep as Android from here - e.g. version 20181212 did not do the hack:
https://sleep.urbandroid.org/wp-content/uploads/release/sleep-20181212-prod-release.apk

@Artaud did you get an update on your Nokia 6.1?

**Comment by Artaud** [comment]
I did get the March update but it did not disable the Power Saver for me on my Nokia 6.1.
My build version is PL2-351F-0-00WW-B04

**Comment by IvanFrederiks** [comment]
@petrnalevka, I installed the old build, hope I will test it this weekend on updated Nokia 6.1. Any suggestions on test conditions?

**Comment by petrnalevka** [comment]
@IvanFrederiks I guess you can simply start sleep tracking and leave it for few hours.. if you get a complete data from the sensor all is fine, i fyou see any red areas in the result - this means the service was killed..

**Comment by Artaud** [comment]
We had the sleep tracking service stopped after about 20 minutes. Also if you set up an alarm for the morning, it only rang very rarely.

**Comment by IvanFrederiks** [comment]
@peternalevka @Artaud
This night everything worked well: tracking completed successfully, Amazfit data was collected. The only thing I tweaked before tracking was to disable battery optimization in app settings.

**Comment by IvanFrederiks** [comment]
@petrnalevka @Artaud
3 nights in a row, everything works fine! Even smart alarm.

**Comment by petrnalevka** [comment]
@IvanFrederiks very interesting, maybe @Artaud can confirm it om his Nokia 6.1?

**Comment by HikariCalyx** [comment]
Thanks you for replying.

A friend of mine @luzhnan , who is using a Nokia 7 Plus with B2N-351F-0-00WW-B04 build installed found a secret about Power Saver G3.
The interface of Power Saver G3 is actually controlled by the overlay placed at "/system/product/overlay/com.evenwell.powersaving.g3.overlay.base.[SKUID].apk".

If you attempt to disable the overlay package, the Power Saver G3 will become into the "Whitelist" Policy like CN releases.

Also, the overlay for SKUID=600CN is attached here.
[com.evenwell.powersaving.g3.overlay.base.600CN.apk.zip](https://github.com/urbandroid-team/dont-kill-my-app/files/3106745/com.evenwell.powersaving.g3.overlay.base.600CN.apk.zip)

**Comment by IvanFrederiks** [comment]
@HikariCalyx do you mean that after 351F update Power Saver G3 uses "Blacklist" policy (which is correct for most cases) and disabling overlay package would be harmful (because "Whitelist" policy does not honor most of apps)?

**Comment by HikariCalyx** [comment]
> @HikariCalyx do you mean that after 351F update Power Saver G3 uses "Blacklist" policy (which is correct for most cases) and disabling overlay package would be harmful (because "Whitelist" policy does not honor most of apps)?

If you disable the overlay instead of the power saver, you'll get Whitelist Policy.

**Comment by IvanFrederiks** [comment]
@petrnalevka, I would like to switch back to most recent version of the app without increasing battery consumption. Is it possible to disable the screen always on hack?

**Comment by petrnalevka** [comment]
@IvanFrederiks many thanks. I did check now and in fact you can do it in settings - misc - disable experimental features.. a side effect it it will also disable some of the latest features of the app.. but hopefully this will help and we will hind something better for the later releases..

**Comment by petrnalevka** [comment]
@HikariCalyx many thanks for the further details we try now to verify it on our Nokia 6.1.. it seems promising, this would be a great news really...

I'm wondering what is the penetration of this update if dev could already rely on it and revert any workarounds they did..

**Comment by Artaud** [comment]
I can confirm that it worked for me on Nokia 6.1 March update, after I again enabled the powersaving.g3.overlay.

**Comment by hb0** [comment]
We have a sensor and location capturing SDK (background process/ForegroundService) and I checked all reviews since May 2019:

I haven't seen any **Nokia** Users reporting background tracking problems.

Last year there were quite a few Nokia user, too. Since May 2019 I only saw Huawai, Xiaomi and some Samsung and OnePlus users report tracking problems, so **it seems like Nokia really did something here** in Europe.

**Comment by petrnalevka** [comment]
Hello, we are also seeing a lot less Nokia issues reported so I'm confirming this on our end. In our apps we have started disabling the hacks we did on Nokia devices. 

I did removed one crap of the Nokia crap score for now and we can improve this further as we see the issue got fully resolved. 

So far I did add a caution text which is explaining this briefly and  links to this thread for details.

Big thanks to everyone and especially to @HikariCalyx for the details on this..

See https://dontkillmyapp.com/nokia

**Comment by homerobse** [comment]
I am using Nokia 6 with build PLE-617G-0-00WW-B01 and still have the problem.

I disabled optimization using these steps:
* Go to Phone Settings > Apps & notifications > Advanced > Special app access > Battery optimization.
* Click on “Not optimized” and in the drop down selection box, choose All apps.
* Scroll down and select Sleep Cycle.
* Choose “Don’t Optimize” instead of optimize.

But the built-in Clock up once in a while does not sound the alarm. Any clue how to solve this for me on the user side?

**Comment by progmars** [comment]
I"m curious about Nokia 8.1 - is it free from this broken Evenwell whitelist/blacklist issue?

**Comment by QXD-me** [comment]
@homerobse See https://www.reddit.com/r/Nokia/comments/di6nqm/nokia_61_psa_if_your_timers_are_going_off_late/

Maybe it's the issue you're having.

"Settings -> Apps & Notifications -> Advanced -> Special app access -> Battery optimization -> pulldown menu "Not optimized" change to "All apps" -> Clock -> "Don't optimize"

This fixed a problem where a 5 minute timer wouldn't go off until 7-8 minutes had passed."
