### ISSUE TITLE
Apply a license to allow other developers to make use of this work

### ISSUE THREAD

**Issue by fennifith** [urbandroid-team/dont-kill-my-app#58]
Sorry for bringing this up again, this issue is related to pull request #43. I think that pull request might be the wrong way to go about applying a license, especially as it leaves the maintainer with little choice of what type of license to use, and this particular pull request contains little explanation of its reasons for being created. However, in response to @Artaud's comment: "isn't no license better than any license if you don't care what will happen with your software?" - a license does not dictate "what will happen to your software", it details how other people should use it and who owns the copyright to its content. By default, your software is not "free for anyone to do what they want", but it is restricted by copyright laws which can then be waived or passed on to other people through the use of a license. With no license, the copyright is owned by Urbandroid and nobody else can legally use it for their purposes.

I would like to express the importance of having a license in this repository, or at the very least a text stating how this content can be used by people who do not hold the copyright (basically, anyone except Urbandroid). If you intend for this content to be useful for the community, an appropriate license is absolutely crucial as it allows developers to use, modify, and redistribute the content for / in their own projects without worrying about the legal burden or liability that comes with it. You can define your own terms of use, such as "make your modifications available under the same license" (a.k.a. copyleft) or "provide a link to our website with the content where it is displayed" as you wish, depending on the license chosen.

For this repository's content, I would recommend a creative commons license (the same as suggested in the pull request), as it is more suited to works that should be "public knowledge" rather than particular / subjective code. 

Here are a few more resources that can help explain why a license is important, and how to choose one:
- ["Why Add a License to your Open Source Project?" - Gareth Wilson, Glitch](https://medium.com/glitch/why-add-a-license-to-your-open-source-project-6f07941f9288)
- ["Open source licensing: What every technologist should know" - Heather Meeker, opensource.com](https://opensource.com/article/17/9/open-source-licensing)
- ["Choosing an open source license" - Neil Chue Hong and Tim Parkinson, Software Sustainability Institute](https://www.software.ac.uk/resources/guides/adopting-open-source-licence)

Currently, this repository contains no license, the effects of which [are detailed here](https://choosealicense.com/no-permission/). This means that nobody can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Some of the legal [limitations and exceptions to copyright](https://en.wikipedia.org/wiki/Limitations_and_exceptions_to_copyright) may apply here, but due to subjectivity and differing local laws surrounding copyright, they should not be relied upon to ensure that others can freely make use of the work that you and the community have done.

**Comment by Artaud** [comment]
Thanks for gathering the arguments. I am really glad for that since my knowledge of licences is basically nonexistent and I always regarded them as a wall of text :)
So I agree that a licence would be good to have.

How would I go about getting the final text of the licence?

**Comment by fennifith** [comment]
There are actually [multiple Creative Commons licenses](https://creativecommons.org/licenses/), each with a slightly different purpose. Which one to use depends on what you hope to achieve, and more importantly what requirements you want derivatives of the work to follow. Here are the full legal texts of the licenses that are listed in that link:

- [CC BY](https://creativecommons.org/licenses/by/4.0/legalcode.txt)
- [CC BY-SA](https://creativecommons.org/licenses/by-sa/4.0/legalcode.txt)
- [CC BY-ND](https://creativecommons.org/licenses/by-nd/4.0/legalcode.txt)
- [CC BY-NC](https://creativecommons.org/licenses/by-nc/4.0/legalcode.txt)
- [CC BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.txt)
- [CC BY-NC-ND](https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.txt)
- [CC0 (Public Domain)](https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt)

You can apply them by simply stating which one it is licensed under and providing a link to the full text wherever the applicable content appears (in this case, I would add it to the footer of the website). A common practice is to place the full text in a `LICENSE` file or on a page of the website so that it is distributed with the content, but I don't believe that this is required.

It is worth noting that the Creative Commons is not intended for software, so (while you certainly _can_) it might not be a good idea to apply it to the entire repository. However, you could simply state in the README that it only applies to the "content" of the website in this case.

**Comment by Artaud** [comment]
Added the CC BY licence and readme text in 7145749769742c616930c0229a62f10f0d8f4c5a and f23af6c8bb61fa043611d08653be880197d7b0a6
