### ISSUE TITLE
Can you please add a section/reference to LG?

### ISSUE THREAD

**Issue by oferRounds** [urbandroid-team/dont-kill-my-app#59]

**Comment by Artaud** [comment]
AFAIK LG does not have any specific killing mechanism other than https://dontkillmyapp.com/general and https://dontkillmyapp.com/google

**Comment by oferRounds** [comment]
Got you. So for our users who face problem on LG, we can direct to these advices?

**Comment by Artaud** [comment]
I would do that. If anything specific on LG shows up later, we'll add a specific section. Thanks for using DKMA!

**Comment by oferRounds** [comment]
Thank you!
