### ISSUE TITLE
Nokia 5.1

### ISSUE THREAD

**Issue by zarandya** [urbandroid-team/dont-kill-my-app#60]
I have a Nokia 5.1 and the Nokia 3.1 solution (DuraSpeed) solved it for me. I also disabled the evenwell power saving apps as shown in the Most Nokia phones section, I don't know if this is necessary or not, but it isn't sufficient.
After restarting my phone, I need to set the setting back to 1 and then 0 again. Setting just to 0 doesn't work, it seems that DuraSpeed only responds to changes in the setting variable, but doesn't read its initial value on startup.

**Comment by polyzen** [comment]
https://github.com/urbandroid-team/dont-kill-my-app/issues/54#issuecomment-483551266

**Comment by kyrasantae** [comment]
> I have a Nokia 5.1 and the Nokia 3.1 solution (DuraSpeed) solved it for me. I also disabled the evenwell power saving apps as shown in the Most Nokia phones section, I don't know if this is necessary or not, but it isn't sufficient.
> After restarting my phone, I need to set the setting back to 1 and then 0 again. Setting just to 0 doesn't work, it seems that DuraSpeed only responds to changes in the setting variable, but doesn't read its initial value on startup.

This issue is discussed in #57 (specifically [this comment](https://github.com/urbandroid-team/dont-kill-my-app/issues/57#issuecomment-483861411)). Probably should reopen that thread...

**Comment by Frauschlau** [comment]
Thank you for the awesome details! I used Macrodroid to stop Duraspeed as explained. Just wondering - is there anything else that is needed? Ifttt and Yonomi still do not run.

**Comment by kyrasantae** [comment]
Unfortunately I don't have experience with either of those apps, so I don't know what else would be needed for them specifically. 

Just to check: Did you also disable the Evenwell power saver app via ADB?

**Comment by Frauschlau** [comment]
Thank you for the immediate response.

I disabled Evenwell via the phone's menu. I gather this is not sufficient, right?

**Comment by kyrasantae** [comment]
Power saver can't be disabled from the phone menu, only force closed. Try [disabling it through ADB](https://dontkillmyapp.com/nokia#user-solution) - I know it says there that fixing DuraSpeed is sufficient, but I'm a bit skeptical (since, for example, the page hasn't been updated to note that it's the toggling that switches off DuraSpeed rather than the variable value itself).

I have both the DuraSpeed and Power saver fixes applied on my device and haven't had any problems.

**Comment by Frauschlau** [comment]
> Power saver can't be disabled from the phone menu, only force closed. Try [disabling it through ADB](https://dontkillmyapp.com/nokia#user-solution) - I know it says there that fixing DuraSpeed is sufficient, but I'm a bit skeptical (since, for example, the page hasn't been updated to note that it's the toggling that switches off DuraSpeed rather than the variable value itself).
> 
> I have both the DuraSpeed and Power saver fixes applied on my device and haven't had any problems.



Sorry to have taken so long to try this and follow up.

I don't think I am having any luck. IFTTT works on and off. Macrodroid seems to stay alive.

To test IFTTT (and I am not that well-versed with all things Android, so this may not be the best way), I used AutomateIt and set up a rule that will say "IFTTT off" if/when the app closes. I heard the announcement as soon as I unplugged the charger. So - I gather this means there is yet something else that is killing background apps.

For Macrodroid - do I understand correctly that I only need to enter the text "setting.duraspeed.enabled = -1", followed by "setting.duraspeed.enabled = 0"? Or do I also need to select any of the "known keys", the option the shows under the "setting key" entry line? And - just to make sure - the "-1" and "0" are to be integers, correct?

Thank you again for your help!

**Comment by kyrasantae** [comment]
Your Macrodroid config sounds fine.

I think you'll need a different way to test IFTTT; if I understand correctly, it's an Android limitation that it's no longer possible (for Macrodroid, at least) to detect whether an app is running in background. It can only detect whether it's in foreground. So it might be that, with your trigger, if it's not on screen when you unplug, it'll fire because it's not in foreground.

I'm afraid I really can't help much more than this, I don't really understand all the technical details, I just know what happens to work for me.

**Comment by Frauschlau** [comment]
> Your Macrodroid config sounds fine.
> 
> I think you'll need a different way to test IFTTT; if I understand correctly, it's an Android limitation that it's no longer possible (for Macrodroid, at least) to detect whether an app is running in background. It can only detect whether it's in foreground. So it might be that, with your trigger, if it's not on screen when you unplug, it'll fire because it's not in foreground.
> 
> I'm afraid I really can't help much more than this, I don't really understand all the technical details, I just know what happens to work for me.
=============================

No worries. I really appreciate your input, help, and the time you spent replying. I will research this further.

Thank you so much!
