### ISSUE TITLE
Question: using `AlertManager` to keep the app alive?

### ISSUE THREAD

**Issue by oferRounds** [urbandroid-team/dont-kill-my-app#61]
I’m not an Android developer myself, so I heard advice about using `AlertManager` to keep the app alive and prevent it from killing the `Foreground service`. Do you think this advice is still relevant these days?

**Comment by petrnalevka** [comment]
Hello, I guess you mean AlarmManager? In many cases the evil battery optimization techniques used by OEM force stop your app which mean all alarms are unscheduled so his is not an option. Moreover many of the techniques focus on providing limits on the AlarmManager so you are no allows to get to foreground at alarm time or too frequent alarms are ignored etc... so I'm afraid this is a no go..

**Comment by oferRounds** [comment]
Oh, sorry, yes! `AlarmManager` :)

And got you :\

Thank you for the reply!
