### ISSUE TITLE
Feedback for Xiaomi page

### ISSUE THREAD

**Issue by Sumaya6789** [urbandroid-team/dont-kill-my-app#633]
Miui 13 khakla ki Korbo plz bolan

**Comment by Rukhsarzeeshan** [comment]
Kiya bol rhi he

**Comment by Sumaya6789** [comment]
আমার ফোনের ভার্সন ১৩ এখন আমি কি করবো আমি অ্যাপসটি চালাতে পারছি না ব্যাগে গেলে আগের মত হয়ে যায়
