### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [urbandroid-team/dont-kill-my-app#65]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by Artaud** [comment]
Hello, sure, why not. Do you mean a Don't kill my app logo or an additional ranking icon? Regarding us, either of those would be nice.

**Comment by Artaud** [comment]
I'll close this issue now, please create a new issue or just mail me at jiri.richter@urbandroid.org for a followup conversation.
