### ISSUE TITLE
Sony stamina mode can be checked

### ISSUE THREAD

**Issue by ElegyD** [urbandroid-team/dont-kill-my-app#66]
According to [this](https://stackoverflow.com/a/50740898/6808319) answer on StackOverflow and [this](https://blog.jakelee.co.uk/how-to-check-if-a-sony-android-device-has-stamina-mode-enabled/) blog post it is possible to detect whether Stamina is on.
But it does only detect if Stamina mode is enabled, not whether this mode is currently in use.
It's an unofficial way, but at least something.

**Comment by petrnalevka** [comment]
Great news.. by thanks for this information. I did update the Sony entry based on your feedback. Please let me know if you have any comments..

https://dontkillmyapp.com/sony
