### ISSUE TITLE
Feedback for OnePlus page

### ISSUE THREAD

**Issue by CaptainColdAJ** [urbandroid-team/dont-kill-my-app#690]
Why is there no update regarding new android versions of any models in this website? Hoping for an update real soon...

**Comment by petrnalevka** [comment]
Hello @CaptainColdAJ  sorry about that, we rely on voluntary contribution by the community, for instance nobody from the maintainers team has a 1+ device, so as seen somebody provides us with updated guides or screenshot we will publish them...
