### ISSUE TITLE
recommendation for cleaner code example on Huawei page 

### ISSUE THREAD

**Issue by 2math** [urbandroid-team/dont-kill-my-app#72]
https://dontkillmyapp.com/huawei#dev-solution
   
    private String lockTag = "com.my_app:LOCK";
    private PowerManager.WakeLock wakeLock = null;

    private void acquireLock() {
        if (wakeLock == null) {
            PowerManager mgr = (PowerManager) getSystemService(Context.POWER_SERVICE);
            if (mgr != null) {

                if (Build.VERSION.SDK_INT == Build.VERSION_CODES.M && Build.MANUFACTURER.equals("Huawei")) {
                    lockTag = "LocationManagerService";
                }

                wakeLock = mgr.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,
                        lockTag);
            }
        }
        if (wakeLock != null && !wakeLock.isHeld()) {
            wakeLock.acquire();//wakeLock.acquire(15*1000);
        }
    }

**Comment by petrnalevka** [comment]
Many thanks, I did use part o your proposed code in the old code to make it more clear..
