### ISSUE TITLE
Huawei Y6 (2019) killing its own Phone app when other apps are in use, incoming calls rejected

### ISSUE THREAD

**Issue by ssb22** [urbandroid-team/dont-kill-my-app#73]
I hope a workaround can be found for this.  My novice friend has just been persuaded by a Virgin Media (UK) saleswoman to buy a Huawei Y6 (2019) running EMUI 9 on a 24-month contract, and we discovered that it rejects incoming phone calls (caller gets told "the number you called is not available" or words to that effect) if and only if another app (such as a browser or email client) is in the foreground.  Incoming phone calls are accepted only if the phone is on the Home Screen at the time of the incoming call.

We believe Huawei's overzealous "battery management" is killing its own Phone app, and have so far not been able to find a workaround (especially since the dialler is not even listed under Apps in the settings).

We don't yet know if this issue was caused by Huawei's default settings or by some change that was made by Virgin Media.

**Comment by ssb22** [comment]
Virgin Mobile somehow managed to solve my friend's problem by sending an over-the-air configuration message to the handset.

Of course the call centre was not equipped to give us any more information about what this OTA message was or why it was needed.

**Comment by Artaud** [comment]
Thanks for this. Without any more information I would believe this might be an issue on part of Virgin so I'll close the issue.
