### ISSUE TITLE
Samsung user instructions are for Android Oreo only

### ISSUE THREAD

**Issue by bubbleguuum** [urbandroid-team/dont-kill-my-app#8]
As per title. Maybe this should be mentioned.

On Samsung's Android Pie, battery saving settings are organized a bit differently.
There seem to be even more of it, in different places, for even more confusion.

**Comment by petrnalevka** [comment]
Big thanks for the update... would you provide us with some updates? We don't have a Pie Samsung around. Screenshots or Settings paths would be great.. many thanks..

**Comment by bubbleguuum** [comment]
Sure I will make screenshots available, but I want to make sure I understand the settings properly first to give an explanation. I'm a developer too deeply impacted by that vendor poop. This is a support nightmare.

**Comment by wormeyman** [comment]
Some screenshots:

![screenshot_20190114-144209_device care](https://user-images.githubusercontent.com/1795016/51146182-f4f5cd80-180a-11e9-88ac-8fbfc4173d82.jpg)
![screenshot_20190114-144216_device care](https://user-images.githubusercontent.com/1795016/51146184-f58e6400-180a-11e9-8310-cecdcb169f74.jpg)
![screenshot_20190114-144229_device care](https://user-images.githubusercontent.com/1795016/51146186-f6bf9100-180a-11e9-891a-9564285c8630.jpg)
![screenshot_20190114-144238_device care](https://user-images.githubusercontent.com/1795016/51146188-f7582780-180a-11e9-8b3c-fa380fc36a21.jpg)
![screenshot_20190114-144245_device care](https://user-images.githubusercontent.com/1795016/51146192-f8895480-180a-11e9-8c9f-25277359131d.jpg)

**Comment by wormeyman** [comment]
Let me know what else you need screenshots of.

**Comment by Artaud** [comment]
closing with 03685b7405581c6d15554f2b582611e2b21dfb15
