### ISSUE TITLE
YouTube premium 

### ISSUE THREAD

**Issue by Mdahahnawaz** [urbandroid-team/dont-kill-my-app#805]
Welcome to Gboard clipboard, any text you copy will be saved here.Tap on a clip to paste it in the text box.Use the edit icon to pin, add or delete clips.Touch and hold a clip to pin it. Unpinned clips will be deleted after 1 hour.

**Comment by Mdahahnawaz** [comment]
YouTube premium op

**Comment by Mdahahnawaz** [comment]
YouTube premium open in my Android device

**Comment by Mdahahnawaz** [comment]
Welcome to Gboard clipboard, any text you copy will be saved here.Tap on a clip to paste it in the text box.Use the edit icon to pin, add or delete clips.Touch and hold a clip to pin it. Unpinned clips will be deleted after 1 hour.

**Comment by einfachdavid89** [comment]
> Welcome to Gboard clipboard, any text you copy will be saved here.Tap on a clip to paste it in the text box.Use the edit icon to pin, add or delete clips.Touch and hold a clip to pin it. Unpinned clips will be deleted after 1 hour.

**Comment by Sakilreja** [comment]
App cannot open 😞

**Comment by Jaykushwaha02** [comment]
Jay

**Comment by Jaykushwaha02** [comment]
Hi my name Jay 
He is good aap
