### ISSUE TITLE
Add wiko and its workaround

### ISSUE THREAD

**Issue by Xpl0itU** [urbandroid-team/dont-kill-my-app#81]
Wiko also kills background apps, none of the methods on the web work, but I found it by myself:
Go to phone assistant/manager
Battery 
Turn off eco. Mode
Go back and go to manual mode
Tap on the gear icon on top right
Background apps whitelist
Now select the apps you don't want to be killed

(Tested on a Wiko U Feel Prime, android 7.1.1)

**Comment by petrnalevka** [comment]
Hello, big thanks for posting this.. I will update the site with your guide do you think you could also post some screenshots? Big thanks..

**Comment by Xpl0itU** [comment]
Oh, also there's another workaround for wiko too,
Go to dialer and put the code "*#*#86569726#*#*" and uncheck "Lowram Enable" And "background enable"

**Comment by petrnalevka** [comment]
Hello, I have added a Wiko entry based on your advice. Big thanks... to have reliable background processes you need to do both the first and the second settings? Screenshots would be great too..

Please see here:
https://dontkillmyapp.com/wiko

**Comment by Xpl0itU** [comment]
You don't have to do both, the second workaround is better than the first though you have to do it everytime you reboot, also, how do I give screenshots?

**Comment by Artaud** [comment]
If you are able to upload the images somewhere like https://pasteboard.co/ then please do so and I'll transfer them to this website...
Thanks

**Comment by Xpl0itU** [comment]
Seems like the code got bad formatted, I uploaded to pastebin: https://pastebin.com/fNYWR4EH (also, don't blame me, it's github's fault)

**Comment by Xpl0itU** [comment]
Also, here are the screenshots: https://drive.google.com/folderview?id=1mkh0SFaM34iBLrzDaP5uIe8Y59j0Ngsl

**Comment by petrnalevka** [comment]
Hello Samuel, many thanks for the update I did add the Wiko screenshots into the wiko entry.. big thanks..

**Comment by Xpl0itU** [comment]
I think you deleted it

**Comment by Xpl0itU** [comment]
The code is still wrong...

**Comment by petrnalevka** [comment]
Sorry, shoudl be fine now..

**Comment by Xpl0itU** [comment]
Nope, and now wiko doesn't show on the index

**Comment by petrnalevka** [comment]
Maybe a cache problem?

**Comment by Xpl0itU** [comment]
It now shows but the code is wrong, did you went to the pastebin url I sent?

**Comment by Artaud** [comment]
Thanks, I fixed the code...it needed a minor adjustment still.
