### ISSUE TITLE
Typo : "install ABD on your computed"

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [urbandroid-team/dont-kill-my-app#84]
Here:
https://dontkillmyapp.com/huawei

I suggest to look for this in the other cases too. 

It's supposed to be:
"install ADB on your computer"

**Comment by louistsaitszho** [comment]
Fixed in #92

**Comment by AndroidDeveloperLB** [comment]
@louistsaitszho Incorrect. I can still see it.

**Comment by Artaud** [comment]
Thanks, fixed by https://github.com/urbandroid-team/dont-kill-my-app/pull/104

**Comment by AndroidDeveloperLB** [comment]
I can see here another :
https://dontkillmyapp.com/samsung
"apps ho rely" . Was probably supposed to be "who", but I think that since those are not people, it should be "which" instead.

**Comment by Artaud** [comment]
Thanks a lot, fixed that
