### ISSUE TITLE
A lot of the settings for MIUI 10 don't seem to exist

### ISSUE THREAD

**Issue by mehdif-git** [urbandroid-team/dont-kill-my-app#9]
"Advanced settings" and "Power Plan" don't seem to exist, I searched in the settings and in the security app and nothing showed, maybe you could add screenshots for the users to see

**Comment by petrnalevka** [comment]
Hello, the issue is we do not have all the Xioami devices - in the fact at the moment we just have a very old MIUI device around. So if you could contribute any updates from your setup we would be grateful for that!..Many thanks..

**Comment by Artaud** [comment]
Hi @Astumed would you have any updates on this?
