### ISSUE TITLE
Why the f*ck is my patched revanced opening website

### ISSUE THREAD

**Issue by Ivonov1** [urbandroid-team/dont-kill-my-app#902]
Pardon my fench😅 but,
WHY IN THE F*CKING UNIVERSE IS MY F*CKING VERSION OF YOUTUBE THAT I F*CKING PATCHED WITH VANCED MANAGER OPENING UP YOUR GOD DAMN F*CKING WEBSITE? 😡😡🤬🤬
So did you guys just inject code into the the patch database just to get more visitors to your _PATHETIC_ website?🤔🤔 Is this some kind of new method of activism?
Sincerely Yours, 
A Revanced User 😆

**Comment by xemulat** [comment]
The ReVanced team did that. It's not injected code, it's a required component from ReVanced GmsCore (better known as MicroG). Close this issue.

**Comment by searinminecraft** [comment]
ah yes one of those troll issues on GitHub...

**Comment by xemulat** [comment]
> ah yes one of those troll issues on GitHub...

Well, you never know for sure...

**Comment by Ivonov1** [comment]
thanks for clarifying. I apologize for the inconvenience. Have a good day
