### ISSUE TITLE
IMPORTANT: Found how to disable battery optimizations on a Tecno brand phone

### ISSUE THREAD

**Issue by CarlosACepeda** [urbandroid-team/dont-kill-my-app#975]
### **Hi, I'd love to contribute to this fantastic project**
There's this aggressive battery restriction on **Tecno Spark** phone that caused something as simple as setting a timer to be completely halted, and foreground services in general.
Like my app was totally frozen! no logcat output or anything.
My app allows for media control, so it was a nightmare to get my app to work correctly on these phones,
there's a setting rather a bit hidden that is enabled by default that once you disable it, the foreground services and simple timers are brought back to life correctly, I want to add this to this Vendor, so more devs can know about this information, thank you!!

**Comment by rl885** [comment]
Hi, do you have any information about Tecno? I can add the vendor to the list, but I need at least some information, ideally screenshots of every "optimization" you found...

**Comment by CarlosACepeda** [comment]
I can put the screenshot of the steps to disable the battery optimization!

**Comment by rl885** [comment]
That would be great - some users prefer to see exactly what they need to disable.

**Comment by petrnalevka** [comment]
Yes a screenshot would be great! Big thanks

**Comment by Dikullya** [comment]
Hello, I don’t see a screenshot on how to disable the battery optimisation, can you put it here?

**Comment by Dikullya** [comment]
Hi, I thought @CarlosACepeda added a screenshot which I don’t see )
